# Generated by Django 6.0.5 on 2026-06-01 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=225)),
                ('course_location', models.CharField(max_length=225)),
                ('day', models.CharField(max_length=225)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('Statistics', 'Statistics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Geology', 'Geology')], max_length=225)),
                ('schedule_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Upcoming', 'Upcoming'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
