# Generated by Django 6.0.5 on 2026-06-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='attendance_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='course_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='geofencing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='level',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='number_of_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='schedule_status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Upcoming', 'Upcoming'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=50),
        ),
    ]
