# Generated by Django 6.0.5 on 2026-06-08 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0002_courseschedule_attendance_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='schedule_status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Upcoming', 'Upcoming'), ('Ended', 'Ended')], default='Upcoming', max_length=50),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=12)),
                ('course_title', models.CharField(max_length=225)),
                ('course_code', models.CharField(default='', max_length=20)),
                ('course_location', models.CharField(max_length=225)),
                ('level', models.CharField(max_length=12)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('longitude', models.FloatField()),
                ('lattitude', models.FloatField()),
                ('token', models.CharField(max_length=6)),
                ('qr_image', models.ImageField(upload_to='qr-code/')),
                ('geofencing', models.IntegerField(default=0)),
                ('schedule_status', models.CharField(choices=[('Session Active', 'Session Active'), ('Session Ended', 'Session Ended')], default='Session Active', max_length=50)),
                ('ended_session', models.BooleanField(default=False)),
                ('total_student', models.IntegerField()),
                ('present', models.IntegerField()),
                ('absent', models.IntegerField()),
                ('expires_at', models.DateTimeField(null=True)),
                ('attendance_rate', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseManagement.courseschedule')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('matric_number', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=12)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('Statistics', 'Statistics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Geology', 'Geology')], max_length=225)),
                ('course_code', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('method', models.CharField(max_length=30)),
                ('time', models.TimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseManagement.courseschedule')),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance_record', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseManagement.attendancesession')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('matric_number', models.CharField(default='', max_length=20)),
                ('level', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('Statistics', 'Statistics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Geology', 'Geology')], default='', max_length=225)),
                ('eligible_for_exam', models.BooleanField(default=False)),
                ('attendance_score', models.IntegerField()),
                ('attendance_percentage', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseManagement.courseschedule')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
