# Generated by Django 6.0.5 on 2026-06-15 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0003_courseschedule_is_elective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcoursecard',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseManagement.courseschedule'),
        ),
    ]
