# Generated by Django 6.0.5 on 2026-06-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0004_alter_studentcoursecard_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='course_title',
            field=models.CharField(default='Database Design', max_length=225),
        ),
    ]
