# Generated by Django 6.0.5 on 2026-06-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='matric_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
