# Generated by Django 6.0.5 on 2026-06-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customuser_matric_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('100 Level', '100 Level'), ('200 Level', '200 Level'), ('300 Level', '300 Level'), ('400 Level', '400 Level')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='matric_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
