# Generated by Django 6.0.5 on 2026-06-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_customuser_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='eligible_for_exam',
        ),
        migrations.AddField(
            model_name='customuser',
            name='minimum_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token_expiration_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_face',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
