# Generated by Django 6.0.5 on 2026-06-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_customuser_eligible_for_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='face_verification',
            field=models.BooleanField(default=False),
        ),
    ]
