# Generated by Django 6.0.5 on 2026-06-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customuser_face_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token_expiration_time',
            field=models.IntegerField(default=30),
        ),
    ]
