# Generated by Django 6.0.5 on 2026-06-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_customuser_token_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_refresh_time',
            field=models.IntegerField(default=10),
        ),
    ]
